OPSWAT Filescan Sandbox integration
anikobartos/sandboxapi pull request #1
Opened 2023-10-20 13:57 UTC by anikobartos

Changed the old OPSWAT integration to the Filescan Sandbox one.
Added some test case and modified the Readme.

2023-10-20 19:03 UTC, petya2164 commented on README.rst
> +`OPSWAT Community Site`_ under API Key tab.
Let's make it more specific:
OPSWAT Community Site => OPSWAT Filescan Community Site

2023-10-20 19:03 UTC, petya2164 commented on sandboxapi/opswat.py
> +# import json
Remove that line, if we don't need the import

2023-10-20 19:04 UTC, petya2164 commented on sandboxapi/opswat.py
> +    # def analyze(self, handle, filename, password = None):
Remove that line

2023-10-20 19:35 UTC, petya2164 commented on sandboxapi/opswat.py
> +        if report_format == "html":
Let's move this check to the start of this function.

2023-10-20 19:36 UTC, petya2164 commented on sandboxapi/opswat.py
> +            "filter=allSignalGroups",
We can add `filter=iocs`.

2023-10-20 19:39 UTC, petya2164 commented on sandboxapi/opswat.py
> +    # instantiate OPSWAT Filescan Sandbox API interface.
I would delete this comment, it does not add any info.

2023-10-20 19:47 UTC, petya2164 commented on sandboxapi/opswat.py
> +        msg = "%s: <url> <api_key> <submit <fh> | available | report <id> | score <report> | analyze <fh>"
Maybe we should clarify these parameters:
url => filescan_url
fh => file_path
id => flow_id

2023-10-20 19:47 UTC, petya2164 commented on sandboxapi/opswat.py
> +    opswat = OPSWATSandboxAPI(api_key)
The url parameter is missing here.

2023-10-20 19:50 UTC, petya2164 commented on sandboxapi/opswat.py
> +    if arg is None:
Let's modify this if:
```
if arg is None and "available" not in cmd:
```

2023-10-20 19:52 UTC, petya2164 commented on sandboxapi/opswat.py
> +        msg = "%s: <url> <api_key> <submit <fh> | available | report <id> | score <report> | analyze <fh>"
report => flow_id

2023-10-20 19:53 UTC, petya2164 commented
Let's rename `item_id` to `flow_id` everywhere!

2023-10-20 19:53 UTC, petya2164 requested changes
See my comments above

2023-10-24 11:25 UTC, anikobartos commented
> Let's rename `item_id` to `flow_id` everywhere!

@petya2164 
I used item_id because in the parent class it is called "item_id" and also in those functions which I need to override.
The other integrations use the same method that I implemented. Eg: cuckoo (id), falcon (job_id), fireeye (file_id), vmray (sample_id or analysis_id), but everybody use item_id.

2023-10-25 12:08 UTC, merged